// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0y7k4b9XlH3yM8U_Zt9MetZvOIvh3j2M',
    appId: '1:25753086120:web:fc0f41567ad5d33fe17a9d',
    messagingSenderId: '25753086120',
    projectId: 'mytestingapp-80c0f',
    authDomain: 'mytestingapp-80c0f.firebaseapp.com',
    storageBucket: 'mytestingapp-80c0f.firebasestorage.app',
    measurementId: 'G-TF8HC7QTK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDke76kakx_z7shSz4yGNxh3J66z3h0p0o',
    appId: '1:25753086120:android:3c9561c46482c8c6e17a9d',
    messagingSenderId: '25753086120',
    projectId: 'mytestingapp-80c0f',
    storageBucket: 'mytestingapp-80c0f.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbuyC1CWGFxq7DeqDieFhgxsfUsyk8c7k',
    appId: '1:25753086120:ios:c959ac422d426649e17a9d',
    messagingSenderId: '25753086120',
    projectId: 'mytestingapp-80c0f',
    storageBucket: 'mytestingapp-80c0f.firebasestorage.app',
    iosBundleId: 'com.example.ifitworksApp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbuyC1CWGFxq7DeqDieFhgxsfUsyk8c7k',
    appId: '1:25753086120:ios:c959ac422d426649e17a9d',
    messagingSenderId: '25753086120',
    projectId: 'mytestingapp-80c0f',
    storageBucket: 'mytestingapp-80c0f.firebasestorage.app',
    iosBundleId: 'com.example.ifitworksApp',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0y7k4b9XlH3yM8U_Zt9MetZvOIvh3j2M',
    appId: '1:25753086120:web:fae050acd6290e91e17a9d',
    messagingSenderId: '25753086120',
    projectId: 'mytestingapp-80c0f',
    authDomain: 'mytestingapp-80c0f.firebaseapp.com',
    storageBucket: 'mytestingapp-80c0f.firebasestorage.app',
    measurementId: 'G-VW0NQ9EGL9',
  );
}
